name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using AI providers."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  API_KEY:
    description: "API key for the selected AI provider (OpenAI or Gemini)"
    required: true
  AI_PROVIDER:
    description: "AI provider to use (openai or gemini)"
    required: true
    default: "gemini"
  MODEL:
    description: "AI model to use (e.g., gpt-4 for OpenAI or gemini-pro for Gemini)"
    required: false
    default: "gemini-pro"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  AVALIAR_TEST_PR:
    description: "Flag para verificar apenas a existência de testes na PR"
    required: false
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
