name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  AI_PROVIDER:
    description: "AI provider to use (openai or gemini)"
    required: false
    default: "openai"
  GOOGLE_API_KEY:
    description: "Google API key for Gemini"
    required: false
  GEMINI_MODEL:
    description: "Gemini model to use"
    required: false
    default: "gemini-pro"
  BOT_NAME:
    description: "Name of the bot that will appear in comments"
    required: false
    default: "quatrodois"
  BOT_IMAGE_URL:
    description: "URL of the bot's avatar image"
    required: false
    default: "https://avatars.githubusercontent.com/u/1324305?v=4"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
