name: Code Review with LLM
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  issue_comment:
    types:
      - created
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Code Review
        uses: fanhubteam/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_PROVIDER: "gemini"
          API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MODEL: "gemini-pro"
          exclude: "yarn.lock,dist/**"
          AVALIAR_TEST_PR: "true"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # Adicione esta linha
