name: Code Review with OpenAI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: freeedcom/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4-1106-preview"
          exclude: "yarn.lock,dist/**"
          BOT_NAME: "quatrodois"
          BOT_IMAGE_URL: "https://avatars.githubusercontent.com/u/123456789?v=4"  # Substitua pela URL da sua imagem
